version: '3'

services:
  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    hostname: cassandra-node1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra-node1-data:/var/lib/cassandra
    networks:
      - cassandra-network

  cassandra-node2:
    image: cassandra:latest
    container_name: cassandra-node2
    hostname: cassandra-node2
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra-node2-data:/var/lib/cassandra
    networks:
      - cassandra-network
    depends_on:
      - cassandra-node1

  cassandra-node3:
    image: cassandra:latest
    container_name: cassandra-node3
    hostname: cassandra-node3
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra-node3-data:/var/lib/cassandra
    networks:
      - cassandra-network
    depends_on:
      - cassandra-node2

  cassandra-node4:
    image: cassandra:latest
    container_name: cassandra-node4
    hostname: cassandra-node4
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra-node4-data:/var/lib/cassandra
    networks:
      - cassandra-network
    depends_on:
      - cassandra-node3

  cassandra-node5:
    image: cassandra:latest
    container_name: cassandra-node5
    hostname: cassandra-node5
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra-node5-data:/var/lib/cassandra
    networks:
      - cassandra-network
    depends_on:
      - cassandra-node4

networks:
  cassandra-network:
    driver: bridge

volumes:
  cassandra-node1-data:
  cassandra-node2-data:
  cassandra-node3-data:
  cassandra-node4-data:
  cassandra-node5-data:
